version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: userdb
      LANG: C.UTF-8
    ports:
      - "5433:5432"
    volumes: 
      - postgres_data_2:/var/lib/postgresql/data

volumes:
  postgres_data_2:
